name: Continuous Integration
on: [push] # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest # Sets the build environment a machine with the latest Ubuntu installed
    steps:
      - uses: actions/checkout@v2 # Adds a step to checkout the repository code

      - name: Restore, Build, test
        uses: Elskom/build-dotnet@main
        with:
          TEST: true
          PACK: false

      - name: Typescript install
        run: npm install
        working-directory: ./DotnetTemplate.Web

      - name: Typescript lint
        run: npm run lint
        working-directory: ./DotnetTemplate.Web

      - name: Typescript test
        run: npm t
        working-directory: ./DotnetTemplate.Web
      
      - name: Report Status
        if: always()
        uses: ravsamhq/notify-slack-action@master
        with:
          status: ${{ job.status }}
          notification_title: '{workflow} has {status_message}'
          message_format: '{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}>'
          footer: 'Linked Repo <{repo_url}|{repo}>'
          notify_when: 'failure,success'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
